baseURL = '//example.org/'
languageCode = 'en-us'
title = 'Anne Wilson'
theme = 'site_theme'

sectionPagesMenu = true

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Projects"
    weight = 0
    url = "/projects/"

